version: '3'
services:
  lb-nginx:
    container_name: lb-nginx
    build:
      context: ./
      dockerfile: ./lb_docker/lb_nginx/nginx_Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
      - "80:80"
    volumes:
      - ~/.sts/logs/nginx:/var/log/nginx
    depends_on:
      - lb-sys
      - lb-admin

  lb-mysql:
    container_name: lb-mysql
    build:
      context: ./
      dockerfile: ./lb_docker/lb_mysql/lb_mysql_Dockerfile
    environment:
      MYSQL_DATABASE: lb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ~/.sts/mysql/mysql_data:/var/lib/mysql
    restart: always

  lb-rabbitmq:
    container_name: lb-rabbitmq
    image: rabbitmq:3.8-rc-management
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./lb_docker/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

  lb-sys:
    container_name: lb-sys
    build:
      context: ./
      dockerfile: ./lb_docker/lb_sys_Dockerfile
    working_dir: /app
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ~/.m2:/root/.m2
      - ./lb_sys:/app/lb_sys
      - ./pom.xml:/app/pom.xml
#      - ~/.sts/logs/server:/app/log #log?
      - ~/.sts/upload:/root/.sts/upload #挂载文件服务
    expose:
      - "9090"
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker -Dmaven.test.skip=true
    depends_on:
      - lb-mysql
      - lb-rabbitmq

  lb-admin:
    container_name: lb-admin
    build:
      context: ./
      dockerfile: ./lb_docker/lb_admin/lb_admin_Dockerfile
    environment:
      TZ: Asia/Shanghai
    expose:
      - "3001"

